######################################################################
# Automatically generated by qmake (3.1) Sat Jul 1 20:50:12 2017
######################################################################

QT += core gui widgets

TEMPLATE = app
TARGET = easycrypt
INCLUDEPATH += .

# Input
FORMS += easycrypt.ui
SOURCES += main.cpp \
    easycrypt.cpp

HEADERS += easycrypt.h

